/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as SessionIdReportRouteImport } from './routes/session.$id.report'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdReportRoute = SessionIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => SessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/sessions': typeof SessionsRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/$id/report': typeof SessionIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/sessions': typeof SessionsRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/$id/report': typeof SessionIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/sessions': typeof SessionsRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/$id/report': typeof SessionIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/sessions'
    | '/setup'
    | '/sitemap.xml'
    | '/session/$id'
    | '/session/$id/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/sessions'
    | '/setup'
    | '/sitemap.xml'
    | '/session/$id'
    | '/session/$id/report'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/sessions'
    | '/setup'
    | '/sitemap.xml'
    | '/session/$id'
    | '/session/$id/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  SessionsRoute: typeof SessionsRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SessionIdRoute: typeof SessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id/report': {
      id: '/session/$id/report'
      path: '/report'
      fullPath: '/session/$id/report'
      preLoaderRoute: typeof SessionIdReportRouteImport
      parentRoute: typeof SessionIdRoute
    }
  }
}

interface SessionIdRouteChildren {
  SessionIdReportRoute: typeof SessionIdReportRoute
}

const SessionIdRouteChildren: SessionIdRouteChildren = {
  SessionIdReportRoute: SessionIdReportRoute,
}

const SessionIdRouteWithChildren = SessionIdRoute._addFileChildren(
  SessionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  SessionsRoute: SessionsRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SessionIdRoute: SessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
